### ISSUE TITLE
Obscure error running the test_xwindow.rb test alone

### ISSUE THREAD

**Issue by Quintus** [Quintus/Automations#2]
The "test_xwindow.rb" test fails with an ArgumentError after it has tested everything: 

<pre>
ruby -I../lib test_xwindow.rb
Loaded suite test_xwindow
Started
..........E

  1) Error:
WindowTest:
ArgumentError: wrong number of arguments (2 for 0)
    /home/marvin/Entpack/Quintus-Automations-813be32/xdo/trunk/lib/xdo/xwindow.rb:385:in `close!'
    test_xwindow.rb:23:in `shutdown'

Finished in 11.667346398 seconds.

10 tests, 10 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
</pre>

**Comment by Quintus** [comment]
This happened due to a missing `require "xdo/keyboard"` and a naming error that caused XWindow#raise to be called instead of Kernel#raise. Fixed in 0.0.3.
